<?php
function get_country_list() {
    return [
        "TR" => "Türkiye", "US" => "Amerika Birleşik Devletleri", "GB" => "Birleşik Krallık", "DE" => "Almanya", "FR" => "Fransa", 
        "AF" => "Afganistan", "AL" => "Arnavutluk", "DZ" => "Cezayir", "AS" => "Amerikan Samoası", "AD" => "Andora", "AO" => "Angola", 
        "AI" => "Anguilla", "AQ" => "Antarktika", "AG" => "Antigua ve Barbuda", "AR" => "Arjantin", "AM" => "Ermenistan", 
        "AW" => "Aruba", "AU" => "Avustralya", "AT" => "Avusturya", "AZ" => "Azerbaycan", "BS" => "Bahamalar", "BH" => "Bahreyn", 
        "BD" => "Bangladeş", "BB" => "Barbados", "BY" => "Belarus", "BE" => "Belçika", "BZ" => "Belize", "BJ" => "Benin", 
        "BM" => "Bermuda", "BT" => "Butan", "BO" => "Bolivya", "BA" => "Bosna Hersek", "BW" => "Botsvana", "BR" => "Brezilya", 
        "IO" => "İngiliz Hint Okyanusu Bölgesi", "BN" => "Brunei", "BG" => "Bulgaristan", "BF" => "Burkina Faso", "BI" => "Burundi", 
        "KH" => "Kamboçya", "CM" => "Kamerun", "CA" => "Kanada", "CV" => "Yeşil Burun Adaları", "KY" => "Cayman Adaları", 
        "CF" => "Orta Afrika Cumhuriyeti", "TD" => "Çad", "CL" => "Şili", "CN" => "Çin", "CX" => "Christmas Adası", 
        "CC" => "Cocos (Keeling) Adaları", "CO" => "Kolombiya", "KM" => "Komorlar", "CG" => "Kongo", "CD" => "Kongo Demokratik Cumhuriyeti", 
        "CK" => "Cook Adaları", "CR" => "Kosta Rika", "CI" => "Fildişi Sahili", "HR" => "Hırvatistan", "CU" => "Küba", 
        "CY" => "Kıbrıs", "CZ" => "Çek Cumhuriyeti", "DK" => "Danimarka", "DJ" => "Cibuti", "DM" => "Dominika", 
        "DO" => "Dominik Cumhuriyeti", "EC" => "Ekvador", "EG" => "Mısır", "SV" => "El Salvador", "GQ" => "Ekvator Ginesi", 
        "ER" => "Eritre", "EE" => "Estonya", "ET" => "Etiyopya", "FK" => "Falkland Adaları (Malvinas)", "FO" => "Faroe Adaları", 
        "FJ" => "Fiji", "FI" => "Finlandiya", "GF" => "Fransız Guyanası", "PF" => "Fransız Polinezyası", "GA" => "Gabon", 
        "GM" => "Gambiya", "GE" => "Gürcistan", "GH" => "Gana", "GI" => "Cebelitarık", "GR" => "Yunanistan", "GL" => "Grönland", 
        "GD" => "Grenada", "GP" => "Guadeloupe", "GU" => "Guam", "GT" => "Guatemala", "GN" => "Gine", "GW" => "Gine-Bissau", 
        "GY" => "Guyana", "HT" => "Haiti", "HN" => "Honduras", "HK" => "Hong Kong", "HU" => "Macaristan", "IS" => "İzlanda", 
        "IN" => "Hindistan", "ID" => "Endonezya", "IR" => "İran", "IQ" => "Irak", "IE" => "İrlanda", "IL" => "İsrail", 
        "IT" => "İtalya", "JM" => "Jamaika", "JP" => "Japonya", "JO" => "Ürdün", "KZ" => "Kazakistan", "KE" => "Kenya", 
        "KI" => "Kiribati", "KP" => "Kuzey Kore", "KR" => "Güney Kore", "KW" => "Kuveyt", "KG" => "Kırgızistan", "LA" => "Laos", 
        "LV" => "Letonya", "LB" => "Lübnan", "LS" => "Lesotho", "LR" => "Liberya", "LY" => "Libya", "LI" => "Lihtenştayn", 
        "LT" => "Litvanya", "LU" => "Lüksemburg", "MO" => "Makao", "MK" => "Makedonya", "MG" => "Madagaskar", "MW" => "Malavi", 
        "MY" => "Malezya", "MV" => "Maldivler", "ML" => "Mali", "MT" => "Malta", "MH" => "Marshall Adaları", "MQ" => "Martinik", 
        "MR" => "Moritanya", "MU" => "Mauritius", "YT" => "Mayotte", "MX" => "Meksika", "FM" => "Mikronezya", "MD" => "Moldova", 
        "MC" => "Monako", "MN" => "Moğolistan", "MS" => "Montserrat", "MA" => "Fas", "MZ" => "Mozambik", "MM" => "Myanmar", 
        "NA" => "Namibya", "NR" => "Nauru", "NP" => "Nepal", "NL" => "Hollanda", "AN" => "Hollanda Antilleri", "NC" => "Yeni Kaledonya", 
        "NZ" => "Yeni Zelanda", "NI" => "Nikaragua", "NE" => "Nijer", "NG" => "Nijerya", "NU" => "Niue", "NF" => "Norfolk Adası", 
        "MP" => "Kuzey Mariana Adaları", "NO" => "Norveç", "OM" => "Umman", "PK" => "Pakistan", "PW" => "Palau", "PS" => "Filistin", 
        "PA" => "Panama", "PG" => "Papua Yeni Gine", "PY" => "Paraguay", "PE" => "Peru", "PH" => "Filipinler", "PL" => "Polonya", 
        "PT" => "Portekiz", "PR" => "Porto Riko", "QA" => "Katar", "RE" => "Reunion", "RO" => "Romanya", "RU" => "Rusya", 
        "RW" => "Ruanda", "SH" => "Saint Helena", "KN" => "Saint Kitts ve Nevis", "LC" => "Saint Lucia", "PM" => "Saint Pierre ve Miquelon", 
        "VC" => "Saint Vincent ve Grenadinler", "WS" => "Samoa", "SM" => "San Marino", "ST" => "Sao Tome ve Principe", "SA" => "Suudi Arabistan", 
        "SN" => "Senegal", "CS" => "Sırbistan ve Karadağ", "SC" => "Seyşeller", "SL" => "Sierra Leone", "SG" => "Singapur", 
        "SK" => "Slovakya", "SI" => "Slovenya", "SB" => "Solomon Adaları", "SO" => "Somali", "ZA" => "Güney Afrika", 
        "ES" => "İspanya", "LK" => "Sri Lanka", "SD" => "Sudan", "SR" => "Surinam", "SZ" => "Svaziland", "SE" => "İsveç", 
        "CH" => "İsviçre", "SY" => "Suriye", "TW" => "Tayvan", "TJ" => "Tacikistan", "TZ" => "Tanzanya", "TH" => "Tayland", 
        "TG" => "Togo", "TO" => "Tonga", "TT" => "Trinidad ve Tobago", "TN" => "Tunus", "TM" => "Türkmenistan", 
        "TC" => "Turks ve Caicos Adaları", "TV" => "Tuvalu", "UG" => "Uganda", "UA" => "Ukrayna", "AE" => "Birleşik Arap Emirlikleri", 
        "UY" => "Uruguay", "UZ" => "Özbekistan", "VU" => "Vanuatu", "VE" => "Venezuela", "VN" => "Vietnam", "VG" => "İngiliz Virgin Adaları", 
        "VI" => "ABD Virgin Adaları", "WF" => "Wallis ve Futuna", "EH" => "Batı Sahra", "YE" => "Yemen", "ZM" => "Zambiya", "ZW" => "Zimbabve"
    ];
}

function get_country_codes() {
    return [
        '+93' => 'Afganistan (+93)',
        '+355' => 'Arnavutluk (+355)',
        '+213' => 'Cezayir (+213)',
        '+376' => 'Andora (+376)',
        '+244' => 'Angola (+244)',
        '+1264' => 'Anguilla (+1264)',
        '+54' => 'Arjantin (+54)',
        '+374' => 'Ermenistan (+374)',
        '+297' => 'Aruba (+297)',
        '+61' => 'Avustralya (+61)',
        '+43' => 'Avusturya (+43)',
        '+994' => 'Azerbaycan (+994)',
        '+1242' => 'Bahamalar (+1242)',
        '+973' => 'Bahreyn (+973)',
        '+880' => 'Bangladeş (+880)',
        '+1246' => 'Barbados (+1246)',
        '+375' => 'Belarus (+375)',
        '+32' => 'Belçika (+32)',
        '+501' => 'Belize (+501)',
        '+229' => 'Benin (+229)',
        '+1441' => 'Bermuda (+1441)',
        '+975' => 'Butan (+975)',
        '+591' => 'Bolivya (+591)',
        '+387' => 'Bosna Hersek (+387)',
        '+267' => 'Botsvana (+267)',
        '+55' => 'Brezilya (+55)',
        '+673' => 'Brunei (+673)',
        '+359' => 'Bulgaristan (+359)',
        '+226' => 'Burkina Faso (+226)',
        '+257' => 'Burundi (+257)',
        '+855' => 'Kamboçya (+855)',
        '+237' => 'Kamerun (+237)',
        '+1' => 'Kanada (+1)',
        '+238' => 'Yeşil Burun Adaları (+238)',
        '+1345' => 'Cayman Adaları (+1345)',
        '+236' => 'Orta Afrika Cumhuriyeti (+236)',
        '+56' => 'Şili (+56)',
        '+86' => 'Çin (+86)',
        '+57' => 'Kolombiya (+57)',
        '+269' => 'Komorlar (+269)',
        '+242' => 'Kongo (+242)',
        '+682' => 'Cook Adaları (+682)',
        '+506' => 'Kosta Rika (+506)',
        '+385' => 'Hırvatistan (+385)',
        '+53' => 'Küba (+53)',
        '+357' => 'Kıbrıs (+357)',
        '+420' => 'Çek Cumhuriyeti (+420)',
        '+45' => 'Danimarka (+45)',
        '+253' => 'Cibuti (+253)',
        '+1767' => 'Dominika (+1767)',
        '+1809' => 'Dominik Cumhuriyeti (+1809)',
        '+593' => 'Ekvador (+593)',
        '+20' => 'Mısır (+20)',
        '+503' => 'El Salvador (+503)',
        '+240' => 'Ekvator Ginesi (+240)',
        '+291' => 'Eritre (+291)',
        '+372' => 'Estonya (+372)',
        '+251' => 'Etiyopya (+251)',
        '+500' => 'Falkland Adaları (+500)',
        '+298' => 'Faroe Adaları (+298)',
        '+679' => 'Fiji (+679)',
        '+358' => 'Finlandiya (+358)',
        '+33' => 'Fransa (+33)',
        '+594' => 'Fransız Guyanası (+594)',
        '+689' => 'Fransız Polinezyası (+689)',
        '+241' => 'Gabon (+241)',
        '+220' => 'Gambiya (+220)',
        '+995' => 'Gürcistan (+995)',
        '+49' => 'Almanya (+49)',
        '+233' => 'Gana (+233)',
        '+350' => 'Cebelitarık (+350)',
        '+30' => 'Yunanistan (+30)',
        '+299' => 'Grönland (+299)',
        '+1473' => 'Grenada (+1473)',
        '+590' => 'Guadeloupe (+590)',
        '+1671' => 'Guam (+1671)',
        '+502' => 'Guatemala (+502)',
        '+224' => 'Gine (+224)',
        '+245' => 'Gine-Bissau (+245)',
        '+592' => 'Guyana (+592)',
        '+509' => 'Haiti (+509)',
        '+504' => 'Honduras (+504)',
        '+852' => 'Hong Kong (+852)',
        '+36' => 'Macaristan (+36)',
        '+354' => 'İzlanda (+354)',
        '+91' => 'Hindistan (+91)',
        '+62' => 'Endonezya (+62)',
        '+98' => 'İran (+98)',
        '+964' => 'Irak (+964)',
        '+353' => 'İrlanda (+353)',
        '+972' => 'İsrail (+972)',
        '+39' => 'İtalya (+39)',
        '+1876' => 'Jamaika (+1876)',
        '+81' => 'Japonya (+81)',
        '+962' => 'Ürdün (+962)',
        '+7' => 'Kazakistan (+7)',
        '+254' => 'Kenya (+254)',
        '+686' => 'Kiribati (+686)',
        '+850' => 'Kuzey Kore (+850)',
        '+82' => 'Güney Kore (+82)',
        '+965' => 'Kuveyt (+965)',
        '+996' => 'Kırgızistan (+996)',
        '+856' => 'Laos (+856)',
        '+371' => 'Letonya (+371)',
        '+961' => 'Lübnan (+961)',
        '+266' => 'Lesotho (+266)',
        '+231' => 'Liberya (+231)',
        '+218' => 'Libya (+218)',
        '+423' => 'Lihtenştayn (+423)',
        '+370' => 'Litvanya (+370)',
        '+352' => 'Lüksemburg (+352)',
        '+853' => 'Makao (+853)',
        '+389' => 'Makedonya (+389)',
        '+261' => 'Madagaskar (+261)',
        '+265' => 'Malavi (+265)',
        '+60' => 'Malezya (+60)',
        '+960' => 'Maldivler (+960)',
        '+223' => 'Mali (+223)',
        '+356' => 'Malta (+356)',
        '+692' => 'Marshall Adaları (+692)',
        '+596' => 'Martinik (+596)',
        '+222' => 'Moritanya (+222)',
        '+230' => 'Mauritius (+230)',
        '+262' => 'Mayotte (+262)',
        '+52' => 'Meksika (+52)',
        '+691' => 'Mikronezya (+691)',
        '+373' => 'Moldova (+373)',
        '+377' => 'Monako (+377)',
        '+976' => 'Moğolistan (+976)',
        '+1664' => 'Montserrat (+1664)',
        '+212' => 'Fas (+212)',
        '+258' => 'Mozambik (+258)',
        '+95' => 'Myanmar (+95)',
        '+264' => 'Namibya (+264)',
        '+674' => 'Nauru (+674)',
        '+977' => 'Nepal (+977)',
        '+31' => 'Hollanda (+31)',
        '+599' => 'Hollanda Antilleri (+599)',
        '+687' => 'Yeni Kaledonya (+687)',
        '+64' => 'Yeni Zelanda (+64)',
        '+505' => 'Nikaragua (+505)',
        '+227' => 'Nijer (+227)',
        '+234' => 'Nijerya (+234)',
        '+683' => 'Niue (+683)',
        '+672' => 'Norfolk Adası (+672)',
        '+1670' => 'Kuzey Mariana Adaları (+1670)',
        '+47' => 'Norveç (+47)',
        '+968' => 'Umman (+968)',
        '+92' => 'Pakistan (+92)',
        '+680' => 'Palau (+680)',
        '+507' => 'Panama (+507)',
        '+675' => 'Papua Yeni Gine (+675)',
        '+595' => 'Paraguay (+595)',
        '+51' => 'Peru (+51)',
        '+63' => 'Filipinler (+63)',
        '+48' => 'Polonya (+48)',
        '+351' => 'Portekiz (+351)',
        '+1787' => 'Porto Riko (+1787)',
        '+974' => 'Katar (+974)',
        '+262' => 'Reunion (+262)',
        '+40' => 'Romanya (+40)',
        '+7' => 'Rusya (+7)',
        '+250' => 'Ruanda (+250)',
        '+590' => 'Saint Barthelemy (+590)',
        '+290' => 'Saint Helena (+290)',
        '+1869' => 'Saint Kitts ve Nevis (+1869)',
        '+1758' => 'Saint Lucia (+1758)',
        '+590' => 'Saint Martin (+590)',
        '+508' => 'Saint Pierre ve Miquelon (+508)',
        '+1784' => 'Saint Vincent ve Grenadinler (+1784)',
        '+685' => 'Samoa (+685)',
        '+378' => 'San Marino (+378)',
        '+239' => 'Sao Tome ve Principe (+239)',
        '+966' => 'Suudi Arabistan (+966)',
        '+221' => 'Senegal (+221)',
        '+381' => 'Sırbistan (+381)',
        '+248' => 'Seyşeller (+248)',
        '+232' => 'Sierra Leone (+232)',
        '+65' => 'Singapur (+65)',
        '+421' => 'Slovakya (+421)',
        '+386' => 'Slovenya (+386)',
        '+677' => 'Solomon Adaları (+677)',
        '+252' => 'Somali (+252)',
        '+27' => 'Güney Afrika (+27)',
        '+34' => 'İspanya (+34)',
        '+94' => 'Sri Lanka (+94)',
        '+249' => 'Sudan (+249)',
        '+597' => 'Surinam (+597)',
        '+268' => 'Svaziland (+268)',
        '+46' => 'İsveç (+46)',
        '+41' => 'İsviçre (+41)',
        '+963' => 'Suriye (+963)',
        '+886' => 'Tayvan (+886)',
        '+992' => 'Tacikistan (+992)',
        '+255' => 'Tanzanya (+255)',
        '+66' => 'Tayland (+66)',
        '+670' => 'Timor-Leste (+670)',
        '+228' => 'Togo (+228)',
        '+690' => 'Tokelau (+690)',
        '+676' => 'Tonga (+676)',
        '+1868' => 'Trinidad ve Tobago (+1868)',
        '+216' => 'Tunus (+216)',
        '+90' => 'Türkiye (+90)',
        '+993' => 'Türkmenistan (+993)',
        '+1649' => 'Turks ve Caicos Adaları (+1649)',
        '+688' => 'Tuvalu (+688)',
        '+256' => 'Uganda (+256)',
        '+380' => 'Ukrayna (+380)',
        '+971' => 'Birleşik Arap Emirlikleri (+971)',
        '+44' => 'Birleşik Krallık (+44)',
        '+1' => 'ABD (+1)',
        '+598' => 'Uruguay (+598)',
        '+998' => 'Özbekistan (+998)',
        '+678' => 'Vanuatu (+678)',
        '+379' => 'Vatikan (+379)',
        '+58' => 'Venezuela (+58)',
        '+84' => 'Vietnam (+84)',
        '+681' => 'Wallis ve Futuna (+681)',
        '+967' => 'Yemen (+967)',
        '+260' => 'Zambiya (+260)',
        '+263' => 'Zimbabve (+263)',
    ];
}
?>